name = "instrument-analysis"
version = "0.1.0"
license = "MIT"
author = "Jane Doe"
maintainer = "paul.gres@gmail.com"
copyright = "Copyright 2023, Paul Gres"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

